drop table "tb_content";
drop table tb_content;

select * from tb_content;

CREATE TABLE "HUANG".tb_content
   (  "id" NUMBER(20,0) NOT NULL ENABLE,
  category_id NUMBER(20,0) NOT NULL ENABLE,
  title NVARCHAR2(200),
  sub_title NVARCHAR2(100),
  title_desc NVARCHAR2(500),
  "url" NVARCHAR2(500),
  pic NVARCHAR2(300),
  pic2 NVARCHAR2(300),
  "content" NCLOB,
  created DATE,
  "updated" DATE,
   PRIMARY KEY ("id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("content") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT));

CREATE UNIQUE INDEX "HUANG"."SYS_C0012218" ON "HUANG".tb_content ("id")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

CREATE INDEX "HUANG"."category_id" ON "HUANG".tb_content (category_id)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

CREATE INDEX "HUANG"."updated" ON "HUANG".tb_content ("updated")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";















  drop table "tb_content_category";

  CREATE TABLE  HUANG.tb_content_category
   (	 "id"  NUMBER(20,0) NOT NULL ENABLE,
	 parent_id  NUMBER(20,0),
	 "name"  NVARCHAR2(50),
	 status  NUMBER(11,0),
	 sort_order  NUMBER(11,0),
	 is_parent  NUMBER(4,0),
	 created  DATE,
	 "updated"  DATE,
	 PRIMARY KEY ( "id" )
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS   ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;

CREATE UNIQUE INDEX  HUANG . SYS_C0012219  ON  HUANG.tb_content_category  ( "id" )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;

CREATE INDEX  HUANG . parent_id  ON  HUANG.tb_content_category  ( parent_id ,  status )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;

CREATE INDEX  HUANG . sort_order  ON  HUANG.tb_content_category  ( sort_order )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;











drop table huang."tb_item";
drop table huang.tb_item;

CREATE TABLE  HUANG.tb_item
   (   "id"  NUMBER(20,0) NOT NULL ENABLE,
   title  NVARCHAR2(100) NOT NULL ENABLE,
   sell_point  NVARCHAR2(500),
   price  NUMBER(20,0) NOT NULL ENABLE,
   num  NUMBER(11,0) NOT NULL ENABLE,
   barcode  NVARCHAR2(30),
   image  NVARCHAR2(500),
   cid  NUMBER(20,0) NOT NULL ENABLE,
   status  NUMBER(4,0) NOT NULL ENABLE,
   created  DATE NOT NULL ENABLE,
   "updated"  DATE NOT NULL ENABLE,
   PRIMARY KEY ( "id" )
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS   ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;

CREATE UNIQUE INDEX  HUANG . SYS_C0012220  ON  HUANG.tb_item( "id" )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;

CREATE INDEX  HUANG . cid  ON  HUANG.tb_item( cid )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;

CREATE INDEX  HUANG . status  ON  HUANG.tb_item  ( status )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;





drop table "tb_item_cat";
drop table tb_item_cat;
CREATE TABLE  HUANG.tb_item_cat
   (   "id"  NUMBER(20,0) NOT NULL ENABLE,
   parent_id  NUMBER(20,0),
   "name"  NVARCHAR2(50),
   status  NUMBER(11,0),
   sort_order  NUMBER(11,0),
   is_parent  NUMBER(4,0),
   created  DATE,
   updated  DATE,
   PRIMARY KEY (  "id" )
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS   ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;

CREATE UNIQUE INDEX  HUANG.SYS_C0012221  ON  HUANG.tb_item_cat  ( "id")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;



drop table "tb_item_desc";
CREATE TABLE  HUANG.tb_item_desc
   (   item_id  NUMBER(20,0) NOT NULL ENABLE,
   item_desc  NCLOB,
   created  DATE,
   updated  DATE,
   PRIMARY KEY ( item_id )
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS   ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS
 LOB ( item_desc ) STORE AS BASICFILE (
  TABLESPACE  USERS  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT));

CREATE UNIQUE INDEX  HUANG.SYS_C0012222  ON  HUANG .tb_item_desc  ( item_id )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;


drop table "tb_item_param";

CREATE TABLE  HUANG . tb_item_param
   (   "id"  NUMBER(20,0) NOT NULL ENABLE,
   item_cat_id  NUMBER(20,0),
   param_data  NCLOB,
   created  DATE,
   "updated"  DATE,
   PRIMARY KEY ( "id" )
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS   ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS
 LOB ( param_data ) STORE AS BASICFILE (
  TABLESPACE  USERS  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT));

CREATE UNIQUE INDEX  HUANG . SYS_C0012223  ON  HUANG .tb_item_param  ( "id" )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;

CREATE INDEX  HUANG . item_cat_id  ON  HUANG .tb_item_param  ( item_cat_id )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;


  drop table "tb_item_param_item";

CREATE TABLE  HUANG . tb_item_param_item
   (   "id"  NUMBER(20,0) NOT NULL ENABLE,
   item_id  NUMBER(20,0),
   param_data  NCLOB,
   created  DATE,
   "updated"  DATE,
   PRIMARY KEY ( "id" )
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS   ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS
 LOB ( param_data ) STORE AS BASICFILE (
  TABLESPACE  USERS  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT));

CREATE UNIQUE INDEX  HUANG . SYS_C0012224  ON  HUANG .tb_item_param_item  ( "id" )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;

CREATE INDEX  HUANG . item_id  ON  HUANG .tb_item_param_item  ( item_id )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)



drop table "tb_order";
CREATE TABLE  HUANG.tb_order
   (   order_id  NVARCHAR2(50) NOT NULL ENABLE,
   payment  NVARCHAR2(50),
   payment_type  NUMBER(11,0),
   post_fee  NVARCHAR2(50),
   status  NUMBER(11,0),
   create_time  DATE,
   update_time  DATE,
   payment_time  DATE,
   consign_time  DATE,
   end_time  DATE,
   close_time  DATE,
   shipping_name  NVARCHAR2(20),
   shipping_code  NVARCHAR2(20),
   user_id  NUMBER(20,0),
   buyer_message  NVARCHAR2(100),
   buyer_nick  NVARCHAR2(50),
   buyer_rate  NUMBER(11,0),
   PRIMARY KEY ( order_id )
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE  USERS   ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE  USERS ;

CREATE UNIQUE INDEX  HUANG . SYS_C0012225  ON  HUANG . tb_order  ( order_id )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE  USERS ;

CREATE INDEX  HUANG . buyer_nick  ON  HUANG .tb_order  ( buyer_nick )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE  USERS ;

CREATE INDEX  HUANG . create_time  ON  HUANG .tb_order  ( create_time )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE  USERS ;

CREATE INDEX  HUANG . payment_type  ON  HUANG .tb_order  ( payment_type )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE  USERS ;

  drop table "tb_order_item";
CREATE TABLE  HUANG . tb_order_item
   (   "id"  NVARCHAR2(20) NOT NULL ENABLE,
   item_id  NVARCHAR2(50) NOT NULL ENABLE,
   order_id  NVARCHAR2(50) NOT NULL ENABLE,
   num  NUMBER(11,0),
   title  NVARCHAR2(200),
   price  NUMBER(20,0),
   total_fee  NUMBER(20,0),
   pic_path  NVARCHAR2(200),
   PRIMARY KEY ( "id" )
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE  USERS   ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE  USERS ;

CREATE UNIQUE INDEX  HUANG . SYS_C0012226  ON  HUANG .tb_order_item  ( "id" )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE  USERS ;

CREATE INDEX  HUANG . order_id  ON  HUANG .tb_order_item  ( order_id )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE  USERS ;


  drop table "tb_order_shipping";
CREATE TABLE  HUANG .tb_order_shipping
   (   order_id  NVARCHAR2(50) NOT NULL ENABLE,
   receiver_name  NVARCHAR2(20),
   receiver_phone  NVARCHAR2(20),
   receiver_mobile  NVARCHAR2(30),
   receiver_state  NVARCHAR2(10),
   receiver_city  NVARCHAR2(10),
   receiver_district  NVARCHAR2(20),
   receiver_address  NVARCHAR2(200),
   receiver_zip  NVARCHAR2(6),
   created  DATE,
   "updated"  DATE,
   PRIMARY KEY ( order_id )
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE  USERS   ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE  USERS ;

CREATE UNIQUE INDEX  HUANG . SYS_C0012227  ON  HUANG .tb_order_shipping  ( order_id )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE  USERS ;

  drop table "tb_user";
CREATE TABLE  HUANG.tb_user
   (   "id"  NUMBER(20,0) NOT NULL ENABLE,
   username  NVARCHAR2(50) NOT NULL ENABLE,
   password  NVARCHAR2(32) NOT NULL ENABLE,
   phone  NVARCHAR2(20),
   email  NVARCHAR2(50),
   created  DATE NOT NULL ENABLE,
   updated  DATE NOT NULL ENABLE,
   PRIMARY KEY ( "id" )
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS   ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;

CREATE UNIQUE INDEX  HUANG . SYS_C0012230  ON  HUANG .tb_user  ( "id" )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;

CREATE UNIQUE INDEX  HUANG . email  ON  HUANG .tb_user  ( email )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;

CREATE UNIQUE INDEX  HUANG . phone  ON  HUANG .tb_user  ( phone )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;

CREATE UNIQUE INDEX  HUANG . username  ON  HUANG .tb_user  ( username )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE  USERS ;



