server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/

  instance:
    instance-id: 消费方服务-9001  # 人性化显示出服务的信息
    prefer-ip-address: true    # 访问路径可显示ip地址
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  application:
    name: ribbon-client




#
#MICROSERVICE-ORDER:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule



